<?php
// Configuration
$USER_COUNT = 100;
$JOB_COUNT = 30;
$HR_USER_ID = 1;
$PASSWORD_HASH = '$2y$10$4oRFX8dxR0zUx9eC2QvQeu2ZrOkb.a7pR2tVAwREUab2Fda8kk8cC'; // password123

$FIRST_NAMES = ["Budi", "Andi", "Siti", "Dewi", "Joko", "Rina", "Agus", "Wati", "Heri", "Lani", "Eko", "Maya", "Rudi", "Ani", "Gali", "Indah", "Dedi", "Lestari", "Ari", "Sari"];
$LAST_NAMES = ["Santoso", "Wijaya", "Kusuma", "Pratama", "Hidayat", "Saputra", "Putri", "Suryani", "Gunawan", "Setiawan", "Lestari", "Wulandari", "Maulana", "Arifin", "Faisal"];

$JOB_TITLES = [
    "Software Engineer", "Frontend Developer", "Backend Developer", "UI/UX Designer", 
    "HR Specialist", "Staff Admin", "Accountant", "Sales Executive", "Marketing Staff",
    "Digital Marketing", "Content Writer", "Graphic Designer", "Project Manager",
    "Data Analyst", "Quality Assurance", "Mobile Developer", "DevOps Engineer",
    "System Administrator", "Public Relations", "Customer Service"
];

$LOCATIONS = ["Jakarta", "Bandung", "Surabaya", "Yogyakarta", "Medan", "Bali", "Semarang", "Makassar", "Tangerang", "Bekasi"];
$RELIGIONS = ["Islam", "Kristen", "Katolik", "Hindu", "Budha", "Konghucu"];
$GENDERS = ["Laki-laki", "Perempuan"];
$EXPERIENCE_LEVELS = ["fresh_grad", "junior_1_3", "mid_3_5", "senior_5_10"];

function escape_sql($val) {
    if ($val === null) return "NULL";
    if (is_numeric($val) && !is_string($val)) return $val;
    return "'" . str_replace("'", "''", $val) . "'";
}

$sql_lines = [
    "-- Bulk Seed Data Generated by Antigravity AI",
    "USE challora_recruitment;",
    "SET FOREIGN_KEY_CHECKS = 0;",
    "",
    "-- PREPARATION: Ensure columns exist (Ignore errors if they already exist)",
    "ALTER TABLE jobs ADD COLUMN IF NOT EXISTS is_dummy TINYINT(1) NOT NULL DEFAULT 0;",
    "ALTER TABLE jobs ADD COLUMN IF NOT EXISTS experience_level VARCHAR(50) DEFAULT NULL;",
    "ALTER TABLE jobs ADD COLUMN IF NOT EXISTS min_salary INT UNSIGNED DEFAULT NULL;",
    "ALTER TABLE jobs ADD COLUMN IF NOT EXISTS max_salary INT UNSIGNED DEFAULT NULL;",
    "",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(20) DEFAULT NULL;",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS religion VARCHAR(50) DEFAULT NULL;",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_place VARCHAR(100) DEFAULT NULL;",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_date DATE DEFAULT NULL;",
    "",
    "TRUNCATE TABLE applications;",
    "DELETE FROM users WHERE role = 'user' AND email LIKE 'user%@example.com';",
    "DELETE FROM jobs WHERE is_dummy = 1;",
    "",
    "-- Ensure at least one HR user exists for FK constraints",
    "INSERT IGNORE INTO users (id, name, email, password, role) VALUES (1, 'HR Admin', 'hr@example.com', '$PASSWORD_HASH', 'hr');",
    "",
    "SET FOREIGN_KEY_CHECKS = 1;",
    ""
];

// Users
$sql_lines[] = "-- Inserting 100 Users";
for ($i = 1; $i <= $USER_COUNT; $i++) {
    $first = $FIRST_NAMES[array_rand($FIRST_NAMES)];
    $last = $LAST_NAMES[array_rand($LAST_NAMES)];
    $name = "$first $last";
    $email = "user$i@example.com";
    $phone = "0812" . rand(10000000, 99999999);
    $address = "Jl. " . $LAST_NAMES[array_rand($LAST_NAMES)] . " No. " . rand(1, 100) . ", " . $LOCATIONS[array_rand($LOCATIONS)];
    $gender = $GENDERS[array_rand($GENDERS)];
    $religion = $RELIGIONS[array_rand($RELIGIONS)];
    $birth_place = $LOCATIONS[array_rand($LOCATIONS)];
    $birth_date = date('Y-m-d', strtotime('-' . rand(20, 45) . ' years'));
    
    $u = [
        "name" => $name,
        "email" => $email,
        "password" => $PASSWORD_HASH,
        "role" => "user",
        "phone" => $phone,
        "address" => $address,
        "gender" => $gender,
        "religion" => $religion,
        "birth_place" => $birth_place,
        "birth_date" => $birth_date
    ];
    
    $cols = implode(", ", array_keys($u));
    $vals = implode(", ", array_map('escape_sql', array_values($u)));
    $sql_lines[] = "INSERT INTO users ($cols) VALUES ($vals);";
}

$sql_lines[] = "";

// Jobs
$sql_lines[] = "-- Inserting 30 Jobs";
for ($i = 1; $i <= $JOB_COUNT; $i++) {
    $title = $JOB_TITLES[array_rand($JOB_TITLES)];
    if ($i % 3 === 0) $title = "Senior $title";
    elseif ($i % 5 === 0) $title = "Head of $title";
    
    $location = $LOCATIONS[array_rand($LOCATIONS)];
    $min_salary = rand(5, 20) * 1000000;
    $max_salary = $min_salary + (rand(2, 10) * 1000000);
    $salary_range = "Rp " . ($min_salary/1000000) . "jt - " . ($max_salary/1000000) . "jt";
    $exp = $EXPERIENCE_LEVELS[array_rand($EXPERIENCE_LEVELS)];
    
    $j = [
        "title" => $title,
        "description" => "Kami sedang mencari $title yang handal untuk bergabung dengan tim kami di $location. Kualifikasi: Minimal " . rand(1, 5) . " tahun pengalaman, mampu bekerja dalam tim, dan memiliki komunikasi yang baik.",
        "location" => $location,
        "salary_range" => $salary_range,
        "is_dummy" => 1,
        "created_by" => "___SUBQUERY_HR___",
        "min_salary" => $min_salary,
        "max_salary" => $max_salary,
        "experience_level" => $exp
    ];
    
    $cols = implode(", ", array_keys($j));
    $vals = [];
    foreach ($j as $k => $v) {
        if ($v === "___SUBQUERY_HR___") {
            $vals[] = "(SELECT id FROM users WHERE role = 'hr' LIMIT 1)";
        } else {
            $vals[] = escape_sql($v);
        }
    }
    $val_str = implode(", ", $vals);
    $sql_lines[] = "INSERT INTO jobs ($cols) VALUES ($val_str);";
}

$sql_lines[] = "";

// Applications
$sql_lines[] = "-- Inserting Applications (2-3 per user)";
for ($i = 1; $i <= $USER_COUNT; $i++) {
    $num_apps = rand(2, 3);
    $job_indices = array_rand(range(0, $JOB_COUNT - 1), $num_apps);
    if (!is_array($job_indices)) $job_indices = [$job_indices];
    
    foreach ($job_indices as $j_idx) {
        $user_sub = "(SELECT id FROM users WHERE email = 'user$i@example.com' LIMIT 1)";
        // We use OFFSET to pick one of the 30 dummy jobs
        $job_sub = "(SELECT id FROM jobs WHERE is_dummy = 1 LIMIT 1 OFFSET $j_idx)";
        $sql_lines[] = "INSERT IGNORE INTO applications (user_id, job_id, cv_path, status) VALUES ($user_sub, $job_sub, 'uploads/cv/dummy_cv.pdf', 'pending');";
    }
}

file_put_contents(__DIR__ . '/../database/seed_bulk_data.sql', implode("\n", $sql_lines));
echo "Successfully generated database/seed_bulk_data.sql\n";
